# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1836ccb65e9a66ac4cc35953c11815ac69c5b020a9af5df779e2589b8eb2a8b27650169837f4c312294ace5fe77172b42911f897cf9793a6fc5caf11d90314e

test:
  secret_key_base: 4a8fa9404f9871243c982bbdb525c0601a6d5418f1f673b15b140a98fe8ab4f848202d9255b5e314b0fc42e3002f42edaa50379e872b3ca752a46b6c4868495d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4a8fa9404f9871243c982bbdb525c0601a6d5418f1f673b15b140a98fe8ab4f848202d9255b5e314b0fc42e3002f42edaa50379e872b3ca752a46b6c4868495d

